server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: resource-service
          uri: http://resource-service:8082
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: health,info